### ISSUE TITLE
crash @ wrong host address

### ISSUE THREAD

**Issue by ananclub** [smallfish/ftp#9]
ftp.go | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/ftp.go b/ftp.go
index d15c962..d88b6d9 100644
--- a/ftp.go
+++ b/ftp.go
@@ -32,10 +32,13 @@ func (ftp *FTP) debugInfo(s string) {
 
 func (ftp *FTP) Connect(host string, port int) {
 	addr := fmt.Sprintf("%s:%d", host, port)
-	ftp.conn, ftp.Error = net.Dial("tcp", addr)
-	ftp.Response()
 	ftp.host = host
 	ftp.port = port
+	ftp.conn, ftp.Error = net.Dial("tcp", addr)
+	if ftp.Error != nil {
+		return
+	}
+	ftp.Response()
 }
 
 func (ftp *FTP) Login(user, passwd string) {

**Comment by smallfish** [comment]
@ananclub thanks for pr :)
